'use client';
import {useMemo,useState} from 'react';
type E={id:string;name:string;role:string;telegram_user_id?:number|null;telegram_chat_id?:number|null};type R=Record<string,any>;
const euro=(x:number)=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'}).format(x||0);const n=(x:any)=>Number(x||0); const label=(a:string)=>a==='OVERHEAD'?'Company overhead':a==='A'?'Project A':'Project B';
async function api(url:string,actor:string,body:any){const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json','x-demo-employee':actor},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error);return j}
export default function Dashboard({employees,sales,expenses}:{employees:E[];sales:R[];expenses:R[]}){
 const [actor,setActor]=useState('');const [message,setMessage]=useState('');const me=employees.find(e=>e.id===actor);const visibleSales=me?.role==='sales'?sales.filter(x=>x.salesperson_id===me.id):me?.role==='expense'?[]:sales;const visibleExpenses=me?.role==='expense'?expenses.filter(x=>x.reporter_id===me.id):me?.role==='sales'?[]:expenses; const [mode,setMode]=useState<'sale'|'expense'>('sale');const [form,setForm]=useState<any>({project:'A',category:'Materials',allocation:'A',richard:50,anastasia:30,jeanClaude:20});
 const stats=useMemo(()=>{const p=(project:string)=>{const ss=visibleSales.filter(x=>x.status==='APPROVED'&&x.project===project),es=visibleExpenses.filter(x=>x.status==='ALLOCATED'&&x.final_allocation===project);const income=ss.reduce((a,x)=>a+n(x.amount),0),commission=ss.reduce((a,x)=>a+n(x.commission_richard)+n(x.commission_anastasia)+n(x.commission_jean_claude),0),expense=es.reduce((a,x)=>a+n(x.amount),0);return{income,commission,expense,result:income-commission-expense}};const A=p('A'),B=p('B'),all=visibleSales.filter(x=>x.status==='APPROVED'),totalSales=all.reduce((a,x)=>a+n(x.amount),0),com=all.reduce((a,x)=>a+n(x.commission_richard)+n(x.commission_anastasia)+n(x.commission_jean_claude),0),overhead=visibleExpenses.filter(x=>x.status==='ALLOCATED'&&x.final_allocation==='OVERHEAD').reduce((a,x)=>a+n(x.amount),0),awaiting=visibleExpenses.filter(x=>x.status==='AWAITING_ALLOCATION').reduce((a,x)=>a+n(x.amount),0);return{A,B,totalSales,com,overhead,awaiting,result:totalSales-com-visibleExpenses.reduce((a,x)=>a+n(x.amount),0)}} ,[visibleSales,visibleExpenses]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();try{if(!actor)throw new Error('Select a demonstration role');const body=mode==='sale'?{kind:'sale',reference:form.reference,customer:form.customer,project:form.project,description:form.description,amount:form.amount,split:{richard:Number(form.richard),anastasia:Number(form.anastasia),jeanClaude:Number(form.jeanClaude)}}:{kind:'expense',reference:form.reference,description:form.description,category:form.category,amount:form.amount,allocation:form.allocation};await api('/api/transactions',actor,body);location.reload()}catch(e){setMessage(e instanceof Error?e.message:'Could not submit')}};
 const decide=async(kind:string,reference:string,record:R)=>{try{if(kind==='sale'){const split={richard:Number(prompt('Richard %',record.proposed_richard)??NaN),anastasia:Number(prompt('Anastasia %',record.proposed_anastasia)??NaN),jeanClaude:Number(prompt('Jean-Claude %',record.proposed_jean_claude)??NaN)};await api('/api/decisions',actor,{kind,reference,split})}else{const allocation=prompt('Final allocation: A, B, or OVERHEAD',record.proposed_allocation);if(!allocation)return;await api('/api/decisions',actor,{kind,reference,allocation})}location.reload()}catch(e){setMessage(e instanceof Error?e.message:'Decision failed')}};
 const retry=async(kind:string,reference:string,delivery:string)=>{try{await api('/api/retry',actor,{kind,reference,delivery});location.reload()}catch(e){setMessage(e instanceof Error?e.message:'Retry failed')}};
 const link=async()=>{try{const emp=prompt('Employee name: Richard, Anastasia, Jean-Claude, Kevin, or Svetlana');const target=employees.find(x=>x.name.toLowerCase()===emp?.toLowerCase());const user=prompt('Telegram user ID');if(!target||!user)throw new Error('Employee and Telegram user ID are required');const chat=prompt('Telegram chat ID (optional, for website-entry notifications)');await api('/api/manager/link',actor,{employeeId:target.id,telegramUserId:user,telegramChatId:chat});location.reload()}catch(e){setMessage(e instanceof Error?e.message:'Link failed')}};
 return <main><header><div><h1>Friends Included finance</h1><p>Wedding Guests for Hire · Supabase source of truth</p></div><label>Demonstration role<select value={actor} onChange={e=>setActor(e.target.value)}><option value="">Select employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name} — {e.role}</option>)}</select></label></header>{message&&<p className="error">{message}</p>}
 <section className="cards"><Card title="Project A" s={stats.A}/><Card title="Project B" s={stats.B}/><article><h2>Company</h2><p>Approved sales <b>{euro(stats.totalSales)}</b></p><p>Commissions <b>{euro(stats.com)}</b></p><p>Overhead <b>{euro(stats.overhead)}</b></p><p>Awaiting allocation <b>{euro(stats.awaiting)}</b></p><strong>Result {euro(stats.result)}</strong></article></section>
 <section className="records"><h2>Commission earned</h2><div className="commission-grid">{['Richard','Anastasia','Jean-Claude'].map((person,key)=>{const column=['commission_richard','commission_anastasia','commission_jean_claude'][key];return <article key={person}><p>{person}</p><strong>{euro(visibleSales.filter(x=>x.status==='APPROVED').reduce((sum,x)=>sum+n(x[column]),0))}</strong></article>})}</div></section>
 <section className="grid"><article><h2>Submit a transaction</h2><div className="tabs"><button onClick={()=>setMode('sale')} className={mode==='sale'?'active':''}>Sale</button><button onClick={()=>setMode('expense')} className={mode==='expense'?'active':''}>Expense</button></div><form onSubmit={submit}><Input name="reference" label="Reference" onChange={form}/>{mode==='sale'?<><Input name="customer" label="Customer" onChange={form}/><Select name="project" label="Project" values={['A','B']} f={form} set={setForm}/><Input name="description" label="Description" onChange={form}/><Input name="amount" label="Amount (€)" type="number" onChange={form}/><div className="split"><Input name="richard" label="Richard %" type="number" onChange={form}/><Input name="anastasia" label="Anastasia %" type="number" onChange={form}/><Input name="jeanClaude" label="Jean-Claude %" type="number" onChange={form}/></div></>:<><Input name="description" label="Description" onChange={form}/><Select name="category" label="Category" values={['Materials','Travel','Other']} f={form} set={setForm}/><Input name="amount" label="Amount (€)" type="number" onChange={form}/><Select name="allocation" label="Proposed allocation" values={['A','B','OVERHEAD']} f={form} set={setForm}/></>}<button type="submit">Submit as {me?.name||'selected role'}</button></form></article>
 <article><h2>Manager setup & instructions</h2><p>Svetlana links Telegram numeric user IDs here. Bot entries retain their original chat ID for later decisions.</p><button disabled={me?.role!=='manager'} onClick={link}>Link Telegram user</button><p className="small">Salespeople: submit sales. Kevin: submit expenses. Svetlana: correct/approve below. Every write is permission checked on the server.</p><p><a href={process.env.NEXT_PUBLIC_TELEGRAM_BOT_URL||'#'}>Telegram bot</a> · <a href={process.env.NEXT_PUBLIC_GOOGLE_SHEET_URL||'#'}>Google Sheet</a> · <a href={process.env.NEXT_PUBLIC_GITHUB_URL||'#'}>GitHub</a></p></article></section>
 <Records title="Sales" rows={visibleSales} kind="sale" manager={me?.role==='manager'} decide={decide} retry={retry}/><Records title="Expenses" rows={visibleExpenses} kind="expense" manager={me?.role==='manager'} decide={decide} retry={retry}/>
 <footer>{process.env.NEXT_PUBLIC_STUDENT_NAME||'Your Name'} · amounts are calculated from the ledger, not test fixtures.</footer></main>}
function Card({title,s}:{title:string;s:any}){return <article><h2>{title}</h2><p>Approved income <b>{euro(s.income)}</b></p><p>Commission expense <b>{euro(s.commission)}</b></p><p>Allocated expenses <b>{euro(s.expense)}</b></p><strong>Result {euro(s.result)}</strong></article>};function Input({name,label,type='text',onChange}:{name:string;label:string;type?:string;onChange:any}){return <label>{label}<input required type={type} onChange={e=>onChange((f:any)=>({...f,[name]:e.target.value}))}/></label>};function Select({name,label,values,f,set}:{name:string;label:string;values:string[];f:any;set:any}){return <label>{label}<select value={f[name]} onChange={e=>set((x:any)=>({...x,[name]:e.target.value}))}>{values.map(x=><option key={x} value={x}>{label==='Proposed allocation'?(x==='A'?'Project A':x==='B'?'Project B':'Company overhead'):x}</option>)}</select></label>}
function Records({title,rows,kind,manager,decide,retry}:{title:string;rows:R[];kind:string;manager:boolean;decide:any;retry:any}){return <section className="records"><h2>{title}</h2>{rows.length===0?<p>No records yet.</p>:<table><thead><tr><th>Reference</th><th>Details</th><th>Amount</th><th>Proposal → final</th><th>Status</th><th>Delivery</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.reference}</td><td>{r.customer?`${r.salesperson?.name}: ${r.customer} · ${r.description}`:`${r.reporter?.name}: ${r.description}`}</td><td>{euro(n(r.amount))}</td><td>{kind==='sale'?`${r.proposed_richard}/${r.proposed_anastasia}/${r.proposed_jean_claude} → ${r.approved_richard==null?'—':`${r.approved_richard}/${r.approved_anastasia}/${r.approved_jean_claude}`}`:`${label(r.proposed_allocation)} → ${r.final_allocation?label(r.final_allocation):'—'}`}</td><td>{r.status}</td><td>Sheets: {r.sheets_state}<br/>Telegram: {r.notification_state}</td><td>{manager&&((kind==='sale'&&r.status==='PENDING')||(kind==='expense'&&r.status==='AWAITING_ALLOCATION'))&&<button onClick={()=>decide(kind,r.reference,r)}>Decide</button>}{manager&&r.sheets_state==='FAILED'&&<button onClick={()=>retry(kind,r.reference,'sheets')}>Retry Sheets</button>}{manager&&r.notification_state==='FAILED'&&<button onClick={()=>retry(kind,r.reference,'telegram')}>Retry Telegram</button>}</td></tr>)}</tbody></table>}</section>}
