import { google } from 'googleapis'; import { db } from './supabase';
const val=(x:unknown)=>x==null?'':String(x);
async function sheets(){const credentials=JSON.parse(process.env.FINANCE_GOOGLE_SERVICE_ACCOUNT_JSON||process.env.GOOGLE_SERVICE_ACCOUNT_JSON||'');const auth=new google.auth.GoogleAuth({credentials,scopes:['https://www.googleapis.com/auth/spreadsheets']});return google.sheets({version:'v4',auth});}
export async function syncRecord(kind:'sale'|'expense',reference:string){
 if(!(process.env.FINANCE_GOOGLE_SHEETS_ID||process.env.GOOGLE_SHEETS_ID))throw new Error('GOOGLE_SHEETS_ID is not configured');const client=await sheets();const table=kind==='sale'?'sales':'expenses';const {data,error}=await db().from(table).select('*, employees!'+(kind==='sale'?'salesperson_id':'reporter_id')+'(name)').eq('reference',reference).single();if(error)throw error;const r:any=data;const tab=kind==='sale'?'Sales':'Expenses';const row=kind==='sale'?[r.reference,r.submitted_at,r.employees.name,r.customer,r.project,r.description,r.amount,`${r.proposed_richard}/${r.proposed_anastasia}/${r.proposed_jean_claude}`,r.approved_richard==null?'':`${r.approved_richard}/${r.approved_anastasia}/${r.approved_jean_claude}`,r.commission_richard,r.commission_anastasia,r.commission_jean_claude,r.status]:[r.reference,r.submitted_at,r.employees.name,r.description,r.category,r.amount,r.proposed_allocation,r.final_allocation??'',r.status];
 const header=kind==='sale'?['Reference','Submission time','Salesperson','Customer','Project','Description','Amount','Original Richard Anastasia Jean Claude split','Approved Richard Anastasia Jean Claude split','Richard earned','Anastasia earned','Jean Claude earned','Status']:['Reference','Submission time','Reporter','Description','Category','Amount','Proposed allocation','Final allocation','Status'];
 const sheetId=process.env.FINANCE_GOOGLE_SHEETS_ID||process.env.GOOGLE_SHEETS_ID!;const got=await client.spreadsheets.values.get({spreadsheetId:sheetId,range:`${tab}!A:A`});const values=got.data.values||[];let index=values.findIndex(x=>x[0]===reference);if(!values.length||values[0][0]!=='Reference'){await client.spreadsheets.values.update({spreadsheetId:sheetId,range:`${tab}!A1`,valueInputOption:'RAW',requestBody:{values:[header]}});index=-1}const range=index>0?`${tab}!A${index+1}`:`${tab}!A${Math.max(2,values.length+1)}`;await client.spreadsheets.values.update({spreadsheetId:sheetId,range,valueInputOption:'RAW',requestBody:{values:[row.map(val)]}});
}
export async function notifyRecord(kind:'sale'|'expense',reference:string){const table=kind==='sale'?'sales':'expenses';const {data:r,error}=await db().from(table).select('*').eq('reference',reference).single();if(error)throw error;if(!r.origin_chat_id)throw new Error('No Telegram recipient linked');const token=process.env.FINANCE_TELEGRAM_BOT_TOKEN||process.env.TELEGRAM_BOT_TOKEN;if(!token)throw new Error('TELEGRAM_BOT_TOKEN is not configured');const changed=kind==='sale'&&(r.proposed_richard!==r.approved_richard||r.proposed_anastasia!==r.approved_anastasia||r.proposed_jean_claude!==r.approved_jean_claude);const text=kind==='sale'?`Sale ${r.reference} approved${changed?' — commission split changed':''}. Sale €${r.amount}; total commission €${(Number(r.commission_richard)+Number(r.commission_anastasia)+Number(r.commission_jean_claude)).toFixed(2)}. Richard: ${r.proposed_richard}% → ${r.approved_richard}% (€${r.commission_richard}). Anastasia: ${r.proposed_anastasia}% → ${r.approved_anastasia}% (€${r.commission_anastasia}). Jean-Claude: ${r.proposed_jean_claude}% → ${r.approved_jean_claude}% (€${r.commission_jean_claude}).`:`Expense ${r.reference}${r.proposed_allocation!==r.final_allocation?' — allocation changed':''}. €${r.amount}: ${r.description}. Proposed: ${r.proposed_allocation}. Approved: ${r.final_allocation}.`;const res=await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:r.origin_chat_id,text})});if(!res.ok)throw new Error(await res.text())}
